# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homeaddress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Home Address'),
        ),
    ]
