# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 05:17
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170102_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='homeaddress',
        ),
        migrations.AlterField(
            model_name='profile',
            name='accounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='资金帐户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='county',
            field=models.CharField(max_length=50, null=True, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮件地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=200, null=True, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.PositiveIntegerField(null=True, verbose_name='销售收入'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='姓氏'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/', verbose_name='用户照片'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(max_length=50, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ship_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='送货地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=200, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=20, null=True, verbose_name='用户类型'),
        ),
    ]
