# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170102_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '详细信息', 'verbose_name_plural': '详细信息'},
        ),
    ]
