# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170103_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[(None, '选择用户类型'), ('customer', '客户'), ('designer', '设计师'), ('maker', '制造商'), ('seller', '销售员')], max_length=20, null=True, verbose_name='用户类型'),
        ),
    ]
