# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_auto_20170108_2211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区县')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.City', verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名字')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓氏')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('address', models.CharField(max_length=250, verbose_name='收货地址')),
                ('postal_code', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid', models.BooleanField(default=False, verbose_name='已支付？')),
                ('received', models.BooleanField(default=False, verbose_name='已收货？')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='orders.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Country')),
                ('county', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='orders.County')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='购买人')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='订单号')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name_plural': '订单内容',
                'verbose_name': '订单内容',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='省份')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Country', verbose_name='国家')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='orders.Province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Province', verbose_name='省份'),
        ),
    ]
