# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家', 'verbose_name_plural': '国家'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': '区县', 'verbose_name_plural': '区县'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份', 'verbose_name_plural': '省份'},
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.CASCADE, to='orders.City', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Country', verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='orders.County', verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='orders.Province', verbose_name='省份'),
        ),
    ]
